"""

Revision ID: 175b9616eb19
Revises: 9a9f8d46ed01
Create Date: 2021-04-27 11:10:34.329720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175b9616eb19'
down_revision = '9a9f8d46ed01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
