"""Add column for usernamee.

Revision ID: 7a9772376dec
Revises: 175b9616eb19
Create Date: 2021-04-27 11:17:10.205553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9772376dec'
down_revision = '175b9616eb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['comment_username'], ['username'])
    op.add_column('pitches', sa.Column('pitch_username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['pitch_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'pitch_username')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'comment_username')
    # ### end Alembic commands ###
