"""Add table for comments.

Revision ID: 900fb82b6729
Revises: 0936420c5058
Create Date: 2021-04-25 17:20:47.768369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900fb82b6729'
down_revision = '0936420c5058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('pitches', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
